#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "Kdthon-ar" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0pNVEhPTi1BUi9KTS1USE9OL2FyY2hpdmUvbWFzdGVyLnppcA=" | base64 -d
    elif [[ $UPSTREAM_REPO == "Kdthon-ar" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0pNVEhPTi1BUi9KTS1USE9OL2FyY2hpdmUvbWFzdGVyLnppcA=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0pNVEhPTi1BUi9KTS1USE9OL2FyY2hpdmUvbWFzdGVyLnppcA=" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="KdthonBot.zip"
    echo "  يتــم تحميــل ملفــآت ســورس كــدثــون  ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  فــك معلــومــآت آلســورس ..."
    KDTHONPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "✓"
    echo "  يتــم آلتفــريــغ .."
    rm -rf "$zippath"
    sleep 5
    cd $KDTHON
    echo "   بــدء بــوت كـدثـون    "
    echo "
                       
╋╋╋╋╋┏┓┏┓
╋┏┳━━┫┗┫┗┳━┳━┳┓
╋┣┫┃┃┃┏┫┃┃╋┃┃┃┃
┏┛┣┻┻┻━┻┻┻━┻┻━┛
┗━┛
    "

    python3 ../setup/update.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot
